spring.application.name=spring-mini-project
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_project
spring.datasource.username=postgres
spring.datasource.password=1234
server.port=9090