spring.application.name=spring-mini-project
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_project
spring.datasource.username=postgres
spring.datasource.password=Solen@123
server.port=9090
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leangk49@gmail.com
spring.mail.password=phnz owsr pztb ifph
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#MINIO CONFIG
minio.url=http://localhost:9000
minio.access.name=UVJGM4XRVZjmJ1iNMHUg
minio.access.secret=8Lx6fr8Vq4YWyxFoGCLZzbyR43TpUeRM1UaTmmaj
minio.bucket.name=mini-project